#!/bin/bash
# Auto-generated by o2 run — do not edit manually
set -e

# $1 = filelist path inside container (e.g. /workdir/filelist.txt)
# $2 = output directory inside container (e.g. /workdir)
FILELIST="${1:?filelist path required}"
OUTPUT_DIR="${2:?output directory required}"

cd "$OUTPUT_DIR"

# DPL pipeline
# DPL pipeline — 8 task(s) activated
o2-analysis-propagationservice | o2-analysis-event-selection-service | o2-analysis-track-to-collision-associator | o2-analysis-trackselection | o2-analysis-multcenttable | o2-analysis-ft0-corrected-table | o2-analysis-trackqa | o2-analysis-je-test-task \
    --aod-file @${FILELIST} \
    --configuration json:///analysis/dpl-config.json \
    -b --run
